esphome:
  name: bewasserung-balkon
  friendly_name: Bewässerung Balkon

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bewasserung-Balkon"
    password: "x"

captive_portal:


# LED on GPIO2 - always ON and not directly controllable
output:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    id: led_output


# Relay on GPIO0 with inverted logic
switch:
  - platform: gpio
    name: "Pump"
    pin:
      number: GPIO0
      inverted: true
    id: relay
    restore_mode: ALWAYS_OFF