esphome:
  name: bewasserung-balkon
  friendly_name: Bewässerung Balkon

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "x"

ota:
  - platform: esphome
    password: "x"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bewasserung-Balkon"
    password: "x"

captive_portal:

############

# LED on GPIO2 - configured as status LED
output:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    id: led_output



# Relay on GPIO0 with inverted logic
switch:
  - platform: gpio
    name: "Pump"
    pin:
      number: GPIO0
      inverted: true
    id: relay
    restore_mode: ALWAYS_OFF


# Standard sensors for monitoring device health
sensor:
  # WiFi signal strength sensor
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: "diagnostic"
  
  # Uptime sensor
  - platform: uptime
    name: "Uptime"
    update_interval: 60s
    entity_category: "diagnostic"
  

# System monitoring and control
button:
  - platform: restart
    name: "Restart"
    entity_category: "config"